project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023, Bryn McLaughlin" 
    right: 
      - icon: github
        href: https://github.com/
  title: "Bryn's Website"
  navbar:
    left:
      - href: index.qmd
        text: My Home
      - about.qmd
      - portfolio.qmd
      - Mapping.qmd
      - walkthrough.qmd
      - newsstory.qmd
      - academic.qmd
      - vaelection_DT.html
      - breaking news story.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



