---
title: "Academic Research"
author: "Bryn McLaughlin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    self-contained: true
    toc: true
    toc-location: left
---

**The following sample is taken from my research essay "*Honor and Love of Ladies: Chivalry in the Age of Shakespeare"*, which details the deterioration of knightly chivalric code in the context of Shakespeare. The essay was presented in the format of an art exhibition, and numbered figures, for example (fig. 2), are referenced throughout the essay regarding artwork that would be included in the exhibition.**

**Chivalry, Women, and Broken Codes of Honor**

The most notable and first organization of knights in British history was the Order of the Garter, founded by King Edward III in 1348. According to legend, the Order was named after an incident at a ball in Calais, France, in which the king's dancing partner's garter fell off on the dance floor. Rather than laugh like other guests at the party, King Edward honorably returned the garter to the lady and said: "honi soit, qui mal y pense," or "Evil be on him who thinks it."^[**\[1\]**](#_ftn1)^ This phrase became the motto of the Order, and exemplifies respect towards women as one of the key values of their knights. This chivalrous view towards women is captured in the *The Booke of Honor and Armes* by Richard Jones, which depicts two knights locked in tournament combat for the "honor and love of ladies" (fig. 8). Just as the martial component of knighthood was romanticised, so too was the amorous component of courtly life. In the 12th century, the Church made two important changes to marriage: it became a sacrament, and was only valid with the consent of both partners.^[\[2\]](#_ftn2)^ Suitors were now able to choose their partners, however their options to exit a marriage were strictly limited; this change led to a focus on *eros* (love) rather than the traditional platonic *agape* relationship.^[\[3\]](#_ftn3)^ As relationships became more focused on attraction and compatibility rather than political and financial calculations, knights were expected to win their lady over through public displays of prowess and valour, particularly in tournament games.^[\[4\]](#_ftn4)^ This tournament 'peacocking' for female attention was based directly off of a scene from Arthurian literature where Sir Lancelot jousts for his watching lady, Guinevere.

In his play *The Merry Wives of Windsor,* Shakespeare directly satirizes knightly values towards respecting women through the character Sir Falstaff, a sorry excuse of a knight who indulges in all the sins from which knights are supposed to abstain. *The Merry Wives of Windsor* was written for Queen Elizabeth to celebrate the Feast of St. George, patron saint of the Order of the Garter, and though the event was solemn Shakespeare chose to make the play a comedy. In the story, the cowardly Falstaff attempts to seduce two married women for personal gain and abuses his status as a knight. The wives are not fooled, but they play along with Falstaff's affections in order to lure him out into the woods, as depicted in Figure 5. On his head Falstaff wears a pair of deer antlers meant to symbolize Hern the Hunter, representing his status as a predator towards women instead of a protector. The women soon get their revenge on Falstaff, however, as children dressed as fairies surround and taunt him, singing:

Fie on sinful fantasy! Fie on lust and luxury! Lust is but a bloody fire, Kindled with unchaste desire, Fed in heart, whose flames aspire, As thoughts do blow them, higher and higher. Pinch him, fairies, mutually! Pinch him for his villainy! Pinch him, and burn him, and turn him about, Till candles, and starlight, and moonshine be out. (5.5.93--102)

This reproachful scene was performed in front of Knights of the Garter themselves, and may have served as a tongue in cheek opportunity for Shakespeare to critique the elite class, disguised as sharp-witted comedy.^[\[5\]](#_ftn5)^ Shakespeare does not criticize the institution of knighthood itself, but rather the failure by individual members who are unable to uphold their organization's key values.

            Another example of the withering standards of knighthood during the Elizabethan era is referenced in *II Henry IV,* when the character Cade dubs himself a knight prior to battle with Sir Humphrey in order to intimidate his opponent.^[\[6\]](#_ftn6)^ This scene is satirizing the disregard for tradition and the honorable actions through which the title of knight is earned, and would likely have resonated with an Elizabethean audience due to a recent scandal involving one of the high-ranking members of the Order of the Garter, Robert Devereux, Earl of Essex (fig. 2). In the portrait Devereux can be seen wearing a jeweled pendant depicting St. George, patron saint of the Order, and his white doublet's color is closely associated with Queen Elizabeth, the Virgin Queen. Though once a favorite of the queen, Devereux began his fall from her favor during his unsuccessful Irish campaign in the 1590s when he hastily created 59 new knights, more than doubling the number existing in the realm and diluting the prestige of the position even further.^[\[7\]](#_ftn7)^ The political indiscretions of Devereux drew criticism from Queen Elizabeth and many others, forcing the public to reevaluate whether members of honorable institutions like the Order were capable of maintaining their chivalric ideals in a shifting social and political landscape.

**Bibliography**

Cartwright, Mark. "Order of the Garter." Ancient History Encyclopedia. Ancient History Encyclopedia, May 3, 2020. <https://www.ancient.eu/Order_of_the_Garter/>.

 "Charles I and the Order of the Garter." *Journal of British Studies* 52, no. 2 (2013): 343-69. Accessed April 16, 2020. [www.jstor.org/stable/41999293](http://www.jstor.org/stable/41999293).

Harlan, Susan. "'Certain Condolements, Certain Vails': Staging Rusty Armour in Shakespeare's *Pericles*." *Early Theatre* 11, no. 2 (September 3, 2014).

HIGHAM, NICHOLAS J. *King Arthur: The Making of the Legend*. NEW HAVEN; LONDON: Yale University Press, 2018. Accessed April 8, 2020. [www.jstor.org/stable/j.ctv7cjvt7](http://www.jstor.org/stable/j.ctv7cjvt7), 217.

"Lance Head for the Joust of Peace." metmuseum.org. The Metropolitan Museum of Art. Accessed May 5, 2020. https://www.metmuseum.org/art/collection/search/24707.

Nickel, Helmut, Stuart W Pyhhr, and Leonid Tarassuk. *The Art of Chivalry: European Arms and The Metropolitan Museum of Art*. New York, NY: The Metropolitan Museum of Art, 1975.

Ortego, James N. "Seeking the Medieval in Shakespeare: The Order of the Garter and the Topos of Derisive Chivalry." In *Fifteenth-Century Studies 35*, edited by Heintzelman Matthew Z., Gusick Barbara I., and Walsh Martin W., 80-104. Rochester, NY; Woodbridge, Suffolk: Boydell & Brewer, 2010. Accessed April 16, 2020. doi:10.7722/j.ctt81rks.10.

Pyhrr, Stuart W., Donald J. LaRocca, and Dirk H. Breiding. *The Armored Horse in Europe, 1480-1620*. New York: Metropolitan Museum of Art, 2005.

SAUL, NIGEL. "Chivalry and Women." In *Chivalry in Medieval England*, 262-82. Cambridge, Massachusetts: Harvard University Press, 2011. Accessed May 5, 2020. [www.jstor.org/stable/j.ctt2jbvtm.19](http://www.jstor.org/stable/j.ctt2jbvtm.19).

SAUL, NIGEL. "The Decline of Chivalry." In *Chivalry in Medieval England*, 347-63. Cambridge, Massachusetts: Harvard University Press, 2011. Accessed May 4, 2020. [www.jstor.org/stable/j.ctt2jbvtm.23](http://www.jstor.org/stable/j.ctt2jbvtm.23).
