---
title: "Interactive Maps"
author: "Bryn McLaughlin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    self-contained: true
    toc: true
    toc-location: left
---
# Here is a walkthrough of how I created an interactive map of Pennsylvania, showing the active labor force distribution by county.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tigris)
library(sf)
library(tidycensus)
library(htmltools)
library(janitor)
library(here)
library(mapview)
library(leafsync)
library(leaflet.extras2)
options(tigris_class = "sf")


```

# Interactive Maps with MapView Package

```{r}

# uncomment to run, then recomment it out so you don't run it every time

#census_api_key("KEY", install=TRUE)


```

```{r}
#chose variables we want
myvars <- c(totalpop = "B01003_001",
            medincome = "B19013_001",
            medage = "B01002_001",
            labor_force = "B23001_001")
```

```{r}
#pull for VA counties
pa_counties_withgeo <- get_acs(geography = "county",
                       variables = c(myvars),
                       state = "PA",
                       output = "wide",
                       geometry = TRUE)

pa_counties_withgeo
```

```{r}
#all counties in the US
all_counties_withgeo <- get_acs(geography = "county",
                       variables = c(myvars),
                       output = "wide",
                       geometry = TRUE)

all_counties_withgeo
```

```{r}
#remove MOE columns - they all end with "M"
pa_counties_withgeo <- pa_counties_withgeo %>%
  select(-ends_with("M"))

pa_counties_withgeo
```

```{r}
#remove that trailing "E"
colnames(pa_counties_withgeo) <- sub("E$", "", colnames(pa_counties_withgeo)) # $ means end of string only

pa_counties_withgeo
```

Mapping Pennsylvania counties with mapview

```{r}

mapview(pa_counties_withgeo, zcol = "labor_force")



```

Customize colors

```{r}

mapview(pa_counties_withgeo, zcol = "labor_force", 
         col.regions = RColorBrewer::brewer.pal(9, "Blues"), 
         alpha.regions = 1)



```

```{r}

map_labor_force <- mapview(pa_counties_withgeo, zcol = "labor_force", 
         col.regions = RColorBrewer::brewer.pal(9, "Blues"), 
         alpha.regions = 1)


```

Customize labels

```{r}

mylabel <- glue::glue("{pa_counties_withgeo$NAM} ")


mapview(pa_counties_withgeo, zcol = "labor_force", 
         col.regions = RColorBrewer::brewer.pal(9, "Greens"), 
         alpha.regions = 1,
         label = mylabel)

```

Customize popups

```{r}
mypopup <- glue::glue("<strong>{pa_counties_withgeo$NAM}</strong><br />
                      Total Population: {pa_counties_withgeo$totalpop}<br />
                     Labor Force Population: {pa_counties_withgeo$labor_force}<br />
                      Median Income: {pa_counties_withgeo$medincome}") %>% 
  lapply(htmltools::HTML)

# mylabel <- glue::glue("{all_data$State} {all_data$PctChange10_20}%") %>%
#   lapply(htmltools::HTML)

```

```{r}

head(mypopup)

```

```{r}

map_labor_force <- mapview(pa_counties_withgeo, zcol = "labor_force", 
         col.regions = RColorBrewer::brewer.pal(9, "Blues"), 
         alpha.regions = 1,
         popup = mypopup)

map_labor_force
```

